//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.21 at 05:30:38 PM GMT+03:30 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.spring.freeland.ir/object", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ir.freeland.spring.object;
